<?php include "header.php"; ?>

<?php

  $program_id = $_GET['program_id'];

  $query = "select * from my_projects where program_id=$program_id";
  $result = mysqli_query($con,$query);

  // Plateform | Program | <Subdomains> Search Trick
  while($row = mysqli_fetch_assoc($result)){

?>


<div class="tables">
    <!-- last appoinments start  -->
    <div class="last-appoinments">
        <div class="heading">
            <h3>Update Program</h3>
        </div><br>

<style>
body {font-family: Arial, Helvetica, sans-serif;}
* {box-sizing: border-box;}

body {
    margin: 0;
    padding: 0;
    overflow: auto; /* Ensure scrolling is enabled */
}


input[type=text], select, textarea {
  width: 100%;
  padding: 12px;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
  margin-top: 6px;
  margin-bottom: 16px;
  resize: vertical;
}

input[type=submit] {
  background-color: #04AA6D;
  color: white;
  padding: 12px 20px;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

input[type=submit]:hover {
  background-color: #45a049;
}

.container {
  border-radius: 5px;
  background-color: #f2f2f2;
}
</style>
</head>
<body>


<div class="container">
  <form action="" method="POST">
    <label for="fname">Program Name</label>
    <input type="text" id="fname" name="program_name" value="<?php echo $row['program_name']; ?>" placeholder="Your name..">

    <label for="subject">Program's Wildcard Domains</label>
    <textarea id="subject" name="program_domains" placeholder="Your Wildcard Domains" style="height:200px"><?php echo $row['program_domains']; ?></textarea>

    <label for="platforms">Program Visibility</label>
    <select id="types" name="program_visiblity">
      <option value="<?php echo $row['program_visiblity']; ?>"><?php echo $row['program_visiblity']; ?></option>
      <option value="Public">Public</option>
      <option value="Private">Private</option>
    </select>


    <label for="platforms">Program Types</label>
    <select id="types" name="program_type">
      <option value="<?php echo $row['program_type']; ?>"><?php echo $row['program_type']; ?></option>
      <option value="VDP">VDP</option>
      <option value="BBP">BBP</option>
    </select>

    <label for="platforms">Bughunting Platforms</label>
    <select id="platforms" name="program_platform">
      <option value="<?php echo $row['program_platform']; ?>"><?php echo $row['program_platform']; ?></option>
      <option value="Hackerone">HackerOne</option>
      <option value="Bugcrowd">BugCrowd</option>
      <option value="YesWeHack">YesWeHack</option>
    </select>

    <label for="subject">Manually Added Subdomains (If Available)</label>
    <textarea id="subject" name="program_manual_subdomains" placeholder="Your Manuall Subdomains" style="height:200px"><?php echo $row['program_manual_subdomains']; ?></textarea>

    <label for="subject">Subdomains (Generated by System)</label>
    <textarea id="subject" name="program_subdomains" placeholder="Your Subdomains" style="height:200px"><?php echo $row['program_subdomains']; ?></textarea>

    <input type="submit" name="update_project" value="Update">
  </form>
</div>

<?php } ?>


<?php

                  if (isset($_POST['update_project'])) {

                  $program_id = $_GET['program_id'];
                  $program_name = $_POST['program_name'];
                  $program_platform = $_POST['program_platform'];
                  $program_visiblity = $_POST['program_visiblity'];
                  $program_type = $_POST['program_type'];
                  $program_domains = $_POST['program_domains'];
                  $program_subdomains = $_POST['program_subdomains'];
                  $program_manual_subdomains = $_POST['program_manual_subdomains'];

                  $query = "UPDATE my_projects SET program_id='$program_id', program_name='$program_name', program_platform='$program_platform', program_visiblity='$program_visiblity', program_type='$program_type', program_domains='$program_domains', program_subdomains='$program_subdomains', program_manual_subdomains='$program_manual_subdomains' WHERE program_id=$program_id";

                  if (mysqli_query($con, $query)) {

                    ?>

                    <script type="text/javascript">alert("Program Updated Successfully")</script>
                    <script type="text/javascript">
                     window.location.href = "http://localhost/lazydb/admin/dashboard.php";
                     </script>

                    <?php

                  } else {
                    echo "Error: " . $sql . "<br>" . mysqli_error($con);
                  }

                  mysqli_close($con);

              }

            ?> 